# Generated by Django 4.1.2 on 2022-10-21 12:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0003_remove_choice_choice_text_remove_choice_question_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='choice',
            name='movie',
        ),
        migrations.AddField(
            model_name='choice',
            name='choice_text',
            field=models.CharField(default='right answer', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='choice',
            name='question',
            field=models.ForeignKey(default='1', on_delete=django.db.models.deletion.CASCADE, to='polls.question'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='question',
            name='movie',
            field=models.ForeignKey(default='1', on_delete=django.db.models.deletion.CASCADE, to='polls.movie'),
            preserve_default=False,
        ),
    ]
